name: Helm Release Pipeline
description: Default template for helm releases to azure aks
inputs:
  K8S_NAMESPACE: 
    description: ''
    required: true
    default: "default"
  HELM_CHART: 
    description: ''
    required: true
    default: "example-golang-webapp"
  ACTION:
    description: 'Acceptable values: deploy/promote/reject. Promote or reject actions are used to promote or reject canary/blue-green deployments.'
    required: true
    default: deploy
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Helm Deploy to AKS
      uses: Azure/k8s-deploy@v1.4
      with:
        namespace: '${{ inputs.K8S_NAMESPACE }}'
        action: ${{ inputs.ACTION }}
        manifests: ''
        strategy: canary
        percentage: 50
        images: ${{ inputs.HELM_CHART }}